-- Run this in your Supabase SQL Editor to create the vendors table

CREATE TABLE vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  company_name TEXT NOT NULL,
  pan_number TEXT,
  gst_number TEXT,
  contact_person TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  escalation_contact TEXT,
  vendor_category TEXT,
  service_capabilities TEXT,
  oem_brands TEXT,
  specialities TEXT,
  tech_team_strength TEXT,
  installed_base TEXT,
  facility_description TEXT,
  missing_items TEXT,
  status TEXT
);

-- Set up Row Level Security (RLS) to allow anonymous inserts
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert rows (so your public form can submit data)
CREATE POLICY "Enable insert for anonymous users" ON vendors
  FOR INSERT
  WITH CHECK (true);

-- Allow only authenticated admins to select (read) the data
CREATE POLICY "Enable read access for authenticated users" ON vendors
  FOR SELECT
  TO authenticated
  USING (true);

-- Allow public users to update their own row if they have the ID
CREATE POLICY "Enable update for anonymous users" ON vendors
  FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Create a secure function to fetch a single vendor by ID and exact Email
CREATE OR REPLACE FUNCTION fetch_vendor_application(p_id BIGINT, p_email TEXT)
RETURNS SETOF vendors
LANGUAGE sql
SECURITY DEFINER -- Runs with elevated privileges to bypass SELECT RLS
AS $$
  SELECT * FROM vendors WHERE id = p_id AND email = p_email LIMIT 1;
$$;

-- Create a secure function to fetch a single vendor by ID or PAN Number and exact Email
CREATE OR REPLACE FUNCTION fetch_vendor_application_by_id_or_pan(p_identifier TEXT, p_email TEXT)
RETURNS SETOF vendors
LANGUAGE sql
SECURITY DEFINER -- Runs with elevated privileges to bypass SELECT RLS
AS $$
  SELECT * FROM vendors 
  WHERE email = p_email 
  AND (id::text = p_identifier OR pan_number = p_identifier) 
  LIMIT 1;
$$;

-- ==========================================
-- SITE CONTENT & REVIEWS SCHEMA
-- ==========================================

CREATE TABLE site_content (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Allow public read access to site content
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON site_content FOR SELECT USING (true);
CREATE POLICY "Enable all access for authenticated users" ON site_content FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  productName TEXT NOT NULL,
  author TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  rating INTEGER NOT NULL,
  verifiedPurchase BOOLEAN DEFAULT false,
  helpfulCount INTEGER DEFAULT 0
);

-- Allow public insert and read for reviews
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable insert for all users" ON reviews FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON reviews FOR SELECT USING (true);
CREATE POLICY "Enable delete for authenticated users" ON reviews FOR DELETE TO authenticated USING (true);

-- Storage bucket for vendor documents
insert into storage.buckets (id, name, public) values ('vendor-documents', 'vendor-documents', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'vendor-documents');
CREATE POLICY "Public Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'vendor-documents');

