-- Run this in your Supabase SQL Editor to create the vendors table

CREATE TABLE vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  company_name TEXT NOT NULL,
  contact_person TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  escalation_contact TEXT,
  vendor_category TEXT,
  service_capabilities TEXT,
  oem_brands TEXT,
  specialities TEXT,
  tech_team_strength TEXT,
  installed_base TEXT,
  facility_description TEXT,
  missing_items TEXT,
  status TEXT
);

-- Set up Row Level Security (RLS) to allow anonymous inserts
ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert rows (so your public form can submit data)
CREATE POLICY "Enable insert for anonymous users" ON vendors
  FOR INSERT
  WITH CHECK (true);

-- Allow only authenticated admins to select (read) the data
CREATE POLICY "Enable read access for authenticated users" ON vendors
  FOR SELECT
  TO authenticated
  USING (true);
